version: "3"

services:
  app:
    image: sms-rest-api-eve
    build:
      context: .
    links: 
      - mongodb
    ports:
      - "8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:8080/_health || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 6
  
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017"
    command: mongod --smallfiles --logpath=/dev/null