version: "3"

services:
  app:
    image: sms-rest-api-eve
    build:
      context: .
    ports:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:8080/_health || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 6